version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: npm run start:dev

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
